version: '3.8'

services:
  obsidiansix-beta:
    build: ./Frontend
    image: obsidian-app:v1
    container_name: obsidiansix-beta
    restart: unless-stopped
    environment:
      HOSTNAME: "0.0.0.0"
      TRUST_PROXY: "true"
      NODE_ENV: "production"
    env_file:
      - ./Frontend/.env
    
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.50' 

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidiansix-beta.rule=Host(`obsidiansix.com`) || Host(`www.obsidiansix.com`)"
      - "traefik.http.routers.obsidiansix-beta.entrypoints=websecure"
      - "traefik.http.routers.obsidiansix-beta.tls=true"
      - "traefik.http.routers.obsidiansix-beta.tls.certresolver=myresolver"
      - "traefik.http.services.obsidiansix-beta.loadbalancer.server.port=3000"

  backend:
    build: ./Backend
    image: obsidian-backend:v1
    container_name: obsidian-backend
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
    env_file:
      - ./Backend/.env
    volumes:
      - /opt/obsidiansix/uploads:/app/uploads
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.obsidiansix.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

networks:
  traefik:
    external: true