/* eslint-disable @next/next/no-page-custom-font */
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`poppins antialiased`}
        cz-shortcut-listen="true"
        data-new-gr-c-s-check-loaded="14.1224.0"
        data-gr-ext-installed=""
      >
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet" />
        {children}
      </body>
    </html>
  );
}
